#!/usr/bin/env python3
"""Executable workflow runner for Flutter Superpowers."""

from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from enum import Enum
from pathlib import Path
from typing import Dict, List, TypedDict, cast


class Phase(str, Enum):
    BRAINSTORM = "brainstorm"
    PLAN = "plan"
    TDD = "tdd"
    IMPLEMENTATION = "implementation"


PHASES = (Phase.BRAINSTORM, Phase.PLAN, Phase.TDD, Phase.IMPLEMENTATION)
STATE_RELATIVE_PATH = Path(".superpowers/workflow/state.json")


class PhaseState(TypedDict):
    completed: bool
    completed_at: str
    artifact: str


class WorkflowState(TypedDict):
    phases: Dict[str, PhaseState]


class WorkflowRunner:
    def __init__(self, base_dir: Path) -> None:
        self.base_dir = base_dir
        self.workflow_dir = self.base_dir / ".superpowers" / "workflow"
        self.state_path = self.base_dir / STATE_RELATIVE_PATH
        self.state = self._load_state()

    def run(self, target_phase: str) -> List[str]:
        try:
            target = Phase(target_phase)
        except ValueError as error:
            raise ValueError(
                f"Unknown phase '{target_phase}'. Choose one of: {', '.join(phase.value for phase in PHASES)}"
            ) from error

        completed_now: List[str] = []
        target_index = PHASES.index(target)
        for phase in PHASES[: target_index + 1]:
            if self.state["phases"].get(phase.value, {}).get("completed"):
                continue
            self._run_phase(phase)
            completed_now.append(phase.value)
        return completed_now

    def _run_phase(self, phase: Phase) -> None:
        self.workflow_dir.mkdir(parents=True, exist_ok=True)
        timestamp = datetime.now(timezone.utc).isoformat()
        artifact_path = self.workflow_dir / f"{phase.value}.md"
        artifact_path.write_text(
            (
                f"# {phase.value.title()} Phase Output\n\n"
                f"- phase: {phase.value}\n"
                f"- completed_at: {timestamp}\n\n"
                "Generated by executable workflow runner.\n"
            ),
            encoding="utf-8",
        )

        self.state["phases"][phase.value] = {
            "completed": True,
            "completed_at": timestamp,
            "artifact": str(artifact_path.relative_to(self.base_dir)),
        }
        self._save_state()

    def _load_state(self) -> WorkflowState:
        if not self.state_path.exists():
            return {"phases": {}}
        loaded = json.loads(self.state_path.read_text(encoding="utf-8"))
        return cast(WorkflowState, loaded)

    def _save_state(self) -> None:
        self.workflow_dir.mkdir(parents=True, exist_ok=True)
        self.state_path.write_text(
            json.dumps(self.state, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Run Flutter Superpowers workflow phases with automatic gate enforcement."
        )
    )
    parser.add_argument(
        "phase",
        nargs="?",
        default=Phase.IMPLEMENTATION.value,
        choices=[phase.value for phase in PHASES],
        help="Target phase to run. Missing prerequisite phases are run automatically.",
    )
    parser.add_argument(
        "--base-dir",
        default=".",
        help="Base directory for writing .superpowers workflow artifacts.",
    )
    return parser


def main() -> int:
    args = build_parser().parse_args()
    runner = WorkflowRunner(base_dir=Path(args.base_dir).resolve())
    completed_now = runner.run(args.phase)
    if completed_now:
        print(f"Completed phases: {', '.join(completed_now)}")
    else:
        print("No new phases needed; target already satisfied.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
